### ISSUE TITLE
ROS2?

### ISSUE THREAD

**Issue by samuk** [PRBonn/agribot#3]
I'm interested in trying https://github.com/PRBonn/agribot/blob/master/doc/api/agribot_visualservoing.md

Under ROS2 on this hardware: https://github.com/samuk/earth_rover_localization#bom-mostly-open-hardware

You planning to upgrade to ROS2?

**Comment by alirezaahmadi** [comment]
We will release a multi-crop row version (python version) but unfortunately there is no plan for taking it to ROS2

**Comment by samuk** [comment]
Thanks, I'll investigate if it might be possible to integrate the visual servoing python version into https://vox-nav.readthedocs.io/en/latest/configuration/index.html as one of the navigation strategies.

**Comment by samuk** [comment]
Seems VOX is not the right way to approach this in ROS2. 

Do you have a rough estimate of when the Python version will be available? Or is there a /dev repo I could take a look at?

Discussing it here: https://discourse.ros.org/t/navigation-for-precision-farming-in-open-fields/15138/13 if you're interested in contributing to that conversation.

**Comment by alirezaahmadi** [comment]
Hi, 

The python version is almost ready but needs to be cleaned up and get ready for getting public, this must happen in a few weeks I would say because I am pretty busy right now. 
Can I ask what is the project your working on?? Maybe I can contribute!! 


Best
Alireza Ahmadi
Research Assistant and Doctoral student
Department of Agricultural Robotics and Engineering
PhenoRob (Cluster of Excellence)
University of Bonn
Nussallee 5, 53115 Bonn, Germany
Tel: +49-(0)288-73-4602
Email: ***@***.***

**Comment by samuk** [comment]
Great, thanks! 

It's not a 'proper' agbot, just a toy really: https://github.com/samuk/Sawppy_Rover/blob/main/modifications/Ag/readme.md

I hope that in time it could develop into something practical & useful.
